# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2f4ec3dbe4ba70b7f17f8afe524509a080859299a1f3508e7737eec7d4627459d93cae7800dbe6099f33fb7a631db98f6b3bd1208f631866f6a410c8b0a27a

test:
  secret_key_base: 55a2ffd5215b677da5ab30f6cbf972b3515f12cf3ba89b60c8310b136aea0c97bef3012a56f0b249a48c89b192fe9ebc78c7c7a0d475285a6c501cc18497e084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
